"""
Django settings for auto_server project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4sb*elwvkro)yjr9*8_brfjx$8hvr%^1bbee%4__j!czvv#jq9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auto_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto_server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

KEY = 'caorui'

PRIV_KEY = b'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWHdJQkFBS0JnUUNXNGJwSFI1VkFwWk5uazZoenVUOWJJTFd5bVlsenlpWHhUc1IxVFU4eityVzd4Rkd3CkExV3NEcnllam52U1cxNlY0WHpNa3JuWlJ0bnEwRzNKVlZrbEVpMHVKMXM2UWNubjB6elUvS2pvTHhjb1pVSUsKVnp1dHJPUmdQOUp1emhKWU1VcUtZRTFPdkFDMmF4ckIwZjdrVnVDbnNLcnd6bmo4VnRqRURXQWZZUUlEQVFBQgpBb0dBUzZiS204ck1qeWwyQzAwQi9XUTQzQncrZmxwMWpOVWl5U2RSWWU5dGN3YVY4SnV5eWFvaVhxN1U3RHRNCjRtQmx3SWphNWtmN1gzSWkrWldmdzQwWHl5cko2N1FJako1a1dodkg2Zm1nQW1lejI1bWsyd1dmKzF4S0dxSXQKN1BQSWlRZGwycjJLWGUxZzhkSnBRSjJJRWM2cjVXNllyaFFvV3k3THcySGlkVEVDUlFEbFA1SWJtOUFVRllhVApuVWhVOUFwU29JZHEwdDA1elE2cG43OVJSS05FdDhteUsvb3NaQ3JFUVVZWExiWlJWSzdMVnlteFJGb0hqSHFsCjM5TkE0NnRBVzduRjR3STlBS2g5Rkg4am51U3V5Ujh1OVNkOVBxclJpVzl6dHZXYjh5cWVCSzVXUHNCV2NJSncKRGpDNUkweU8vNlJmZlI2YXN4MVhOQ2JuN09naE5TUW82d0pFZmdCYjJRcmg2amdPbU5ISThOQ1ZYK2JWcDFRdwp2ZFZFS3QwZnRaWkpPcnJkaEMyQnVxWnZqeURsV2xZSXNGa2dIYWxSeEJueWRkV3pqN29mRGJwVTVQSEZnTXNDClBIeVBTOUhhUWFPS1hBR0RzNVdvRCtZMDFrZmc0Z2VkYlIyNmlIZGlKeTRHT1ZNVkNFaVk5akdwSGZFazd0anIKUVRPVnZtWnMyMFdaRnpKT1ZRSkVJNDk2ZFhNTk1xMkVtOEZnWWFlSE8xL0JFTnkyazlVQnVPV1huejJ3TGZiUQovcndEc1c3UFBZVU44UWF1S2ZReTd4dVluQUliRVNqZndJUU1PeGJrc0RCK1Nvaz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K'

LENGTH = 1024
RSA_LENGTH = int(LENGTH / 8)
ENABLE_LENGTH = RSA_LENGTH - 11
